name: Bolt Egress Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bolt by Koalalab
        uses: koalalab-inc/bolt@v1.7.0
